strive/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, except: [:index]
  resource :session, only: [:new, :create, :destroy]
end

strive/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

strive/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint(8)        not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  after_initialize :ensure_session_token
  validates :username, :password_digest, :session_token, presence: true
  validates :username, uniqueness: true
  validates :password, length:{minimum: 6, allow_nil: true, message: "Password must be at least 6 characters."}
  attr_reader :password
  
  def self.find_by_credentials(username, pw)
    user = User.find_by(username: username)
    if user && user.is_password?(pw)
      return user
    end
    nil
  end  
  
  def is_password?(pw)
    BCrypt::Password.new(self.password_digest).is_password?(pw)
  end
  
  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end
  
  def reset_session_token
    self.session_token = SecureRandom.urlsafe_base64
    self.save!
    self.session_token
  end
  
  def password=(pw)
    @password = pw
    self.password_digest = BCrypt::Password.create(pw)
  end

end

strive/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?
  # before_action :require_login
  
  def current_user
    return nil if session[:session_token].nil?
    @current_user ||= User.find_by(session_token: session[:session_token])
  end
  
  def login(user)
    session[:session_token] = user.reset_session_token
    current_user
  end
  
  def logout 
    current_user.reset_session_token
    session[:session_token] = nil
    @current_user = nil
  end
  
  def logged_in?
    !!current_user
  end
  
  def require_login
    redirect_to new_session_url unless logged_in?
  end
  
  # def require_logout
  #   redirect_to new_session_url if logged_in?
  # end
end

strive/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    before_action :require_login, only: [:logout]
  def new
  end
  
  def create
    user = User.find_by_credentials(params[:username],params[:password])
    if user
      login(user)
      redirect_to user_url(user)
    else
      flash.now[:errors] = ["Invalid login credentials"]
      render :new
    end
  end
  
  def destroy
    logout
    redirect_to new_session_url
  end
end

strive/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, except: [:new, :create]

  def new
    render :new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      session[:session_token] = @user.reset_session_token
      redirect_to user_url(@user)
    else
      flash.now[:errors] = ["Invalid username or password"]
      render :new
    end
  end
  
  def show
    @user = User.find_by(id: params[:id])
  end
  
  def edit
    @user = User.find_by(id: params[:id])
    render :edit
  end
  
  def update
    # byebug
    @user = User.find_by(id: params[:id])
    if @user.update(user_params)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = ["Invalid username or password"]
      render :edit
    end
  end
  
  def destroy
    @user = User.find_by(id: params[:id])
    @user.destroy
    render :new
  end
  
  private
  
  def user_params
    params.require(:user).permit(:username,:password)
  end
end

strive/app/helpers/application_helper.rb
module ApplicationHelper
  
  def auth_token
    tag = "<input type='hidden' name='authenticity_token' value='#{form_authenticity_token}'>".html_safe
  end
  
  
end

strive/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Strive</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <% if logged_in? %>
        <h1> Welcome, <a href=" <%= user_url(current_user) %> "> <%= current_user.username %></a> </h1>
        <form action=" <%= session_url %>" method="post">
          <input type="hidden" name="_method" value="delete">
          <%= auth_token %>
          <input type="submit" value="Log out!">
        </form>
      <% else %>
      <!-- <h1>Login or sign up below! <%#= request.original_fullpath %> </h1> -->
        <% unless request.original_fullpath == "/users/new" %>
          <form action=" <%= new_user_url %>" method="post">
            <input type="hidden" name="_method" value="get">
            <input type="submit" value="Sign up!">
          </form>
        <% end %>
        <% unless request.original_fullpath == "/session/new" %>
          <form action=" <%= new_session_url %>" method="post">
            <input type="hidden" name="_method" value="get">
            <input type="submit" value="Log in!">
          </form>
        <% end %>
      <% end %>
    </header>
    
    <% if flash[:errors] %>
      <% flash[:errors].each do |error| %>
        <%= error %>
      <% end %>
    <% end %>
    
    <%= yield %>
    
  </body>
</html>

strive/app/views/users/edit.html.erb
<h2>Welcome! You are editing your profile, <%= @user.username %>. </h2>

<form action="<%= user_url(@user) %>" method="post">
  
  <input type="hidden" name="_method" value="patch">
  <%= auth_token %>
  
  <label>Change your username:</label>
  <input id="username" type="text" name="user[username]" value="<%= @user.username %>">
  
  
  <input type="submit" value="Update my info!">
  
</form>

strive/app/views/users/new.html.erb
<h1>Welcome! Sign up below</h1>

<form action="<%= users_url %>" method="post">
  
  <%= auth_token %>
  
  <label>Username:</label>
  <input id="username" type="text" name="user[username]">

  <label>Password:</label>
  <input id="password" type="password" name="user[password]">
  
  
  <input type="submit" value="Sign up!">
  
</form>

strive/app/views/users/show.html.erb
<h2>This is your profile, <%= @user.username %>!</h2>

<form action=" <%= edit_user_url(@user) %>" method="post">
  <input type="hidden" name="_method" value="get">
  <input type="submit" value="Edit user info!">
</form>